apiVersion: v1
kind: Pod
metadata:
  name: no-op
  labels:
    app: no-op
spec:
  containers:
    - name: ubi9
      image: registry.redhat.io/ubi9/ubi:latest
      command: ["sleep", "infinity"]
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
        requests:
          cpu: "10m"
          memory: "16Mi"
